name 'motd-ubuntu'
maintainer 'The Authors'
maintainer_email 'you@example.com'
license 'all_rights'
description 'Installs/Configures motd-ubuntu'
long_description 'Installs/Configures motd-ubuntu'
version '0.1.0'
